### ISSUE TITLE
HTML tags not working in footnotes

### ISSUE THREAD

**Issue by stormpork** [kadamwhite/civil-footnotes#10]
Hi, I love this plugin, but after a recent update HTML tags aren't working anymore. The tags themselves are being displayed instead of applied.

**Comment by kadamwhite** [comment]
@stormpork thanks for the bug report! Can you give me an example of the markup that isn’t rendering for you?

**Comment by stormpork** [comment]
I can't show you the active site right now because I had to revert to v1.3.1, but in my case it was just formatting tags like < em > that weren't rendering. I noticed that other users might be having similar issues with other html too.

I'm not a developer or a wiz with Wordpress, hopefully it's not something I'm doing wrong. All I did was disabled other plugins and created new posts, but the problem remained.

If it'll really assist you understanding the issue, I can re-update back to 2.0 and show you through the active site with the issue...

**Comment by n4al** [comment]
<img width="793" alt="Captura de pantalla 2019-11-14 a las 12 27 41" src="https://user-images.githubusercontent.com/731358/68853437-46484500-06da-11ea-99e7-d1478db9356f.png">
Here is an example. Let me know if it is helpful or I should produce a better one. The actual code is:
`((</p>
Value of OPEC holdings in the West ($ billion)
<div>

<img title="Table for Note 8 in Chapter IV"  alt="Table for Note 8 in Chapter IV" width="690" height="226" />
<div></div>
</div>
This figure was estimated by the British magazine Business Week in 1981, before the recent fall in crude oil prices.
<p style="text-align: justify;">))`

**Comment by kadamwhite** [comment]
Version 2.1, released today, should fix this problem. Thank you for calling out the bug and my apologies for my delayed response. Please comment here if you find the issue is not resolved.
