### ISSUE TITLE
HTML not working in footnote

### ISSUE THREAD

**Issue by gilstudent** [kadamwhite/civil-footnotes#9]
In the latest update, my HTML formatting is showing as code. For example, < em > appears as part of the footnote rather than formatting the text in italics. How can I get the HTML to format?

Thank you

**Comment by kadamwhite** [comment]
Version 2.1, released today, should fix this problem. Thank you for calling out the bug and my apologies for my delayed response. Please comment here if you find the issue is not resolved.
